spring:
  datasource:
    url: jdbc:mysql://goorm-db.ch0tdwjy4tz5.ap-northeast-2.rds.amazonaws.com:3306/goorm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: sju093475#
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000